name: CI
on: push
jobs:
  test:
    name: mix test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    strategy:
      matrix:
        # elixir: ['1.9.4', '1.10.4', '1.10.x', '1.11.4', '1.11.x', '1.12.2', '1.12.x']
        elixir: ['1.12.x']
        include:
        # - elixir: '1.9.4'
        #   otp: '22.x'
        # - elixir: '1.10.4'
        #   otp: '22.x'
        # - elixir: '1.10.x'
        #   otp: '23.x'
        # - elixir: '1.11.4'
        #   otp: '22.x'
        # - elixir: '1.11.x'
        #   otp: '23.x'
        # - elixir: '1.12.1'
        #   otp: '23.x'
        - elixir: '1.12.x'
          otp: '24.x'
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-elixir@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Run Tests
      run: mix test

    - name: Run Credo
      run: mix credo --strict

    - name: Fetch PLT Cache
      uses: actions/cache@v2
      with:
        path: priv/plts
        key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ hashFiles('**/mix.lock') }}
    - name: Generate PLTs
      if: steps.fetch-plt-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p priv/plts
        mix dialyzer --plt
    - name: Run Dialyzer
      run: mix dialyzer --no-check
