name: CI (Legacy Elixir versions)
on: push
jobs:
  test:
    name: mix test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    strategy:
      matrix:
        elixir: ['1.5.0', '1.5.3', '1.6.6', '1.6.x', '1.7.4', '1.8.2']
        include:
        - elixir: '1.5.0'
          otp: '20.x'
        - elixir: '1.5.3'
          otp: '20.x'
        - elixir: '1.6.6'
          otp: '20.x'
        - elixir: '1.6.x'
          otp: '21.x'
        - elixir: '1.7.4'
          otp: '21.x'
        - elixir: '1.8.2'
          otp: '21.x'
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-elixir@v1
      with:
        otp-version: ${{ matrix.otp }}
        elixir-version: ${{ matrix.elixir }}

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get --only=test

    - name: Run Tests
      run: mix test
